// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221124181015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Channel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e02e9e66-c226-4b12-9ed2-effb4ab2287b"),
                            Description = "Canal dedicado a dotnet core",
                            Name = "DotnetCore"
                        },
                        new
                        {
                            Id = new Guid("b9a7f9fa-7d12-4806-8b51-cd73433de54d"),
                            Description = "Canal dedicado a Angular",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("15a7c214-3ee0-4bc5-a5fb-ff383a82089b"),
                            Description = "Canal dedicado a Reactjs",
                            Name = "Reactjs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
